# Generated by Django 3.2.12 on 2022-05-24 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_id', models.IntegerField()),
                ('movie_like', models.ManyToManyField(related_name='movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
